parameters:
#    hvp_core_model.example.class: HVP\CoreModelBundle\Example

services:
#    hvp_core_model.example:
#        class: %hvp_core_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
