hvp_core_api:
    resource: "@HVPCoreApiBundle/Resources/config/routing.yml"
    prefix:   /api

hvp_core_model:
    resource: "@HVPCoreModelBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
