HVP\CoreModelBundle\Entity\Holder:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        extId:
            type: string
            length: '100'
        extType:
            type: string
            length: '32'
    oneToMany:
        HolderReferences:
            targetEntity: HolderReference
            mappedBy: Holder
        ProductInstances:
            targetEntity: ProductInstance
            mappedBy: Holder
    lifecycleCallbacks: {  }
