HVP\CoreModelBundle\Entity\Product:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: '32'
        extId:
            type: string
            length: '100'
        extType:
            type: string
            length: '32'
    oneToMany:
        ProductInstances:
            targetEntity: ProductInstance
            mappedBy: Product
        ProductEvents:
            targetEntity: ProductEvent
            mappedBy: Product	
    lifecycleCallbacks: {  }
