parameters:
#    hvp_core_api.example.class: HVP\CoreApiBundle\Example

services:
#    hvp_core_api.example:
#        class: %hvp_core_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
